name: Deploy Main

on:
  push:
    branches: [ Main ]  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Run the workflow on a Linux virtual machine

    steps:
      - uses: actions/checkout@v3  # Checkout the repository code
      - name: Use Node.js 14  # Adjust Node.js version as needed (if applicable)
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install dependencies
        run: npm install  # Or yarn install, depending on your preference
      - name: Build the React app
        run: npm run build  # Or yarn build
      - name: Deploy to VPS using SSH (Secure with SSH Key)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: '8.222.212.29'
          username: 'root'  # Consider using a non-privileged user for deployment
          key: ${{ secrets.SSH_P_KEY }}  # Reference the secret holding your private key
          script: |
            cd /var/www/html  # Replace with the directory on your VPS
            rm -rf *  # Use with caution, consider a more specific pattern
            cp -r $GITHUB_WORKSPACE/dist/* .  # Copy files from dist to VPS
            # Optional: ls  # List files in the directory (for debugging)
            sudo systemctl restart httpd  # Restart Apache (adjust command if using a different web server)
