name: Deploy React App

on:
  push:
    branches: [ Main ]  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Run the workflow on a Linux virtual machine

    steps:
      - uses: actions/checkout@v3  # Checkout the repository code
      - name: Use Node.js 14  # Adjust Node.js version as needed (if applicable)
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install dependencies
        run: npm install  # Or yarn install, depending on your preference
      - name: Build the React app
        run: npm run build  # Or yarn build
      - name: Deploy to VPS using rsync
        uses: burnett01/rsync-deployments@7.0.0
        with:
          switches: '-avzr'  # Optional rsync flags (archive, verbose, compress, delete)
          path: 'build'  # Replace with your built project directory
          remote_path: '/var/www/html'  # Replace with your deployment path on VPS
          remote_host: '8.222.212.29'  # Replace with your VPS host address
          remote_user: 'root'  # Replace with your username on VPS
          remote_key: ${{ secrets.SSH_P_KEY }}  # Encrypted private key secret
      - name: Connect to VPS and Restart httpd (Optional)
        uses: nlohmann/action-ssh@v2  # Or your preferred SSH action
        if: always()  # Run this step even if previous steps fail
        with:
          host: ${{ secrets.VPS_HOST }}  # Consider using a separate secret for the host
          username: ${{ secrets.VPS_USERNAME }}  # Consider using a separate secret for the username
          key: ${{ secrets.SSH_P_KEY }}  # Encrypted private key secret
          script: |
            sudo systemctl restart httpd  # Adjust command for your web server (e.g., nginx)
